# NumPy Tutorial in Colab

## Introduction

NumPy is a powerful library for numerical operations in Python. It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays.

In this tutorial, we'll cover the following topics:

1. Creating Arrays
2. Array Operations
3. Array Indexing and Slicing
4. Shape and Reshaping
5. Mathematical Functions

Let's get started!

## 1. Creating Arrays

NumPy arrays are the core data structure. You can create arrays using various methods.

```python

In [2]:

import numpy as np

# Create a 1D array
arr_1d = np.array([1, 2, 3])

# Create a 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

# Create an array with zeros
zeros_array = np.zeros((3, 3))

# Create an array with ones
ones_array = np.ones((2, 2))

# Create an array with a range of values
range_array = np.arange(0, 10, 2)  # from 0 to 10 with a step of 2

# Display the created arrays
arr_1d, arr_2d, zeros_array, ones_array, range_array


(array([1, 2, 3]),
 array([[1, 2, 3],
        [4, 5, 6]]),
 array([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]),
 array([[1., 1.],
        [1., 1.]]),
 array([0, 2, 4, 6, 8]))

2. Array Operations

In [4]:
# Element-wise addition
result_addition = arr_1d + arr_2d

# Element-wise multiplication
result_multiplication = arr_1d * arr_2d

# Dot product of two arrays
dot_product = np.dot(arr_1d, arr_2d.T)  # Transposing arr_2d to make the shapes compatible


# Display the results
result_addition, result_multiplication, dot_product


(array([[2, 4, 6],
        [5, 7, 9]]),
 array([[ 1,  4,  9],
        [ 4, 10, 18]]),
 array([14, 32]))

In [5]:
# Access a specific element
element = arr_2d[0, 1]  # 2

# Slice the array
slice_arr = arr_2d[:, 1]  # array([2, 5])

# Display the results
element, slice_arr


(2, array([2, 5]))

In [6]:
# Get the shape of the array
shape = arr_2d.shape  # (2, 3)

# Reshape the array
reshaped_arr = arr_2d.reshape((3, 2))

# Display the results
shape, reshaped_arr


((2, 3),
 array([[1, 2],
        [3, 4],
        [5, 6]]))

In [7]:
# Square root of each element
sqrt_arr = np.sqrt(arr_1d)

# Exponential of each element
exp_arr = np.exp(arr_1d)

# Sum, mean, and standard deviation
sum_arr = np.sum(arr_1d)
mean_arr = np.mean(arr_1d)
std_arr = np.std(arr_1d)

# Display the results
sqrt_arr, exp_arr, sum_arr, mean_arr, std_arr


(array([1.        , 1.41421356, 1.73205081]),
 array([ 2.71828183,  7.3890561 , 20.08553692]),
 6,
 2.0,
 0.816496580927726)